// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
import productsFilterController from "./products_filter_controller"
import crewsController from "./crews_controller"
application.register("hello", HelloController)
application.register("product_filter", productsFilterController)
application.register("crews", crewsController)

